# Generated by Django 5.2.5 on 2025-08-31 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_apiuser_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='feedbacks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=[], size=None),
        ),
    ]
