# Generated by Django 5.2.5 on 2025-09-01 08:33

import db.models.user
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_apiuser_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('specialization', models.CharField(max_length=255, verbose_name='Specialization within the Job Title')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('checklist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.AlterModelManagers(
            name='apiuser',
            managers=[
                ('objects', db.models.user.APIUserManager()),
            ],
        ),
    ]
