# Generated by Django 5.2.5 on 2025-09-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_onboardcatalog_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardcatalog',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialization within the Job Title'),
        ),
    ]
