# Generated by Django 5.2.5 on 2025-09-01 10:03

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_create_pgvector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardcatalog',
            name='specialization_vector',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='onboardcatalog',
            name='tags_vector',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='onboardcatalog',
            name='title_vector',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
