# Generated by Django 5.2.5 on 2025-09-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_create_pgvector_extension'),
        ('db', '0009_onboardcatalog_specialization_vector_and_more'),
    ]

    operations = [
    ]
