# Generated by Django 5.2.5 on 2025-09-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_merge_20250901_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='job_title',
            field=models.CharField(null=True, verbose_name='Job Title of the employee'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='specialization',
            field=models.CharField(blank=True, null=True, verbose_name='Specialization of the employee'),
        ),
    ]
