# Generated by Django 5.2.5 on 2025-09-02 10:18

import django.contrib.postgres.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_apiuser_job_title_apiuser_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Skill Title')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None)),
                ('type', models.CharField(max_length=16, verbose_name='Resource Type')),
                ('url', models.URLField(verbose_name='Resource URL')),
                ('title_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('tags_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('type_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
            ],
        ),
    ]
