# Generated by Django 5.2.5 on 2025-09-12 18:33

import django.contrib.postgres.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_skillcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='improvements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='improvements_vector',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='strengths_vector',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
