# Generated by Django 5.2.5 on 2025-09-12 19:25

import django.contrib.postgres.fields
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_apiuser_improvements_apiuser_improvements_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='improvements_vector',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='improvements_vector_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=pgvector.django.vector.VectorField(dimensions=384, null=True), default=list, size=None),
        ),
    ]
