# Generated by Django 5.2.5 on 2025-09-12 20:40

import django.contrib.postgres.fields
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_alter_apiuser_improvements_vector_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='improvements_vector_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=pgvector.django.vector.VectorField(dimensions=384), blank=True, default=list, null=True, size=None),
        ),
    ]
