# Generated by Django 5.2.5 on 2025-09-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_alter_apiuser_improvements_vector_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='improvements_vector_list',
        ),
    ]
