# Generated by Django 5.2.5 on 2025-09-12 21:40

import django.contrib.postgres.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_remove_apiuser_improvements_vector_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, help_text='Key skills/tech stack for this role', size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, help_text='e.g., Intern, Junior, Mid, Senior, Staff, Principal', max_length=64, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('title_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('specialization_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('skills_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('aggregate_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
