# Generated by Django 5.2.5 on 2025-09-12 22:03

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_openrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrole',
            name='description_vector',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
