# Generated by Django 5.2.5 on 2025-09-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_openrole_description_vector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenRole',
        ),
    ]
