# Generated by Django 5.2.5 on 2025-09-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_delete_openrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='strengths_vectors',
            field=models.JSONField(default=list, help_text='List of individual strength vectors'),
        ),
    ]
