# Generated by Django 5.2.5 on 2025-09-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_add_individual_strengths_vectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='strengths_vectors',
        ),
    ]
