# Generated by Django 5.2.5 on 2025-09-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_remove_strengths_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='onboard_supp_hr_query',
            field=models.CharField(blank=True, null=True, verbose_name='Supplementary query by the HR for the employee'),
        ),
    ]
