# Generated by Django 5.2.5 on 2025-09-22 19:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_apiuser_onboard_supp_hr_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='onboard_completed_checklist_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='onboard_finalized',
            field=models.BooleanField(blank=True, null=True, verbose_name="If the employee's onboard items have been finalized by the employee"),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='onboard_json',
            field=models.JSONField(blank=True, null=True, verbose_name='The customized onboard items for this employee'),
        ),
    ]
