# Generated by Django 5.2.5 on 2025-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_apiuser_onboard_completed_checklist_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('completed_onboard_tasks', models.IntegerField(default=0, verbose_name='Amount of onboard tasks completed by the employees')),
                ('assigned_onboard_tasks', models.IntegerField(default=0, verbose_name='Total number of onboard tasks assigned to the employees')),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
