# Generated by Django 5.2.5 on 2025-09-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='flagged_feedbacks_count',
            field=models.IntegerField(default=0, verbose_name='The number of feedbacks flagged as biased'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='pii_redacted_count',
            field=models.IntegerField(default=0, verbose_name='The number of PII info redacted'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='prompt_injection_count',
            field=models.IntegerField(default=0, verbose_name='The amount of prompt injection attempts this months'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='total_feedbacks_count',
            field=models.IntegerField(default=0, verbose_name='The total number of feedbacks added to the system'),
        ),
    ]
