# Generated by Django 5.2.5 on 2025-09-23 05:29

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_kpi_flagged_feedbacks_count_kpi_pii_redacted_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill_title', models.TextField()),
                ('skill_description', models.TextField(blank=True)),
                ('learning_outcomes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('resources', models.JSONField(default=list)),
                ('title_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
