# Generated by Django 5.2.5 on 2025-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_negativefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='job_level',
            field=models.IntegerField(default=1, verbose_name='The job level of the person'),
        ),
    ]
